"""
Generated by: cdrca install pythonmaster / pythonmaster new

This is normal Python. PythonMaster does not restrict what you can do
here — import whatever packages you need, add whatever routes you want,
swap SQLite in db.py for any other database. The only thing PythonMaster
asks of this file is that it read PORT from the environment (so
`pythonmaster run` can pick a free port for you) and serve the project
when run directly.

`pythonmaster run` starts this file with:
    PORT=<port> PYTHONMASTER_RELOAD=1 python main.py
and prints the port it chose to stdout as `CDRCA_PORT=<port>`.
`PYTHONMASTER_RELOAD=1` enables uvicorn's auto-reload for local dev;
`pythonmaster run --prod` omits it.
"""

import os

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

import db

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app = FastAPI(title="CDRCA PythonMaster App")

db.init_db(
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL
    );
    """
)
if not db.find("users"):
    db.create("users", {"name": "Ada"})
    db.create("users", {"name": "Grace"})


# ---------------------------------------------------------------------
# Example API routes, backed by db.py (SQLite).
#
# Matches the example in the pythonmaster CDRCA plugin's README:
#   pythonapi getUsers = GET "/api/users"
#   pythonapi createUser = POST "/api/users"
# in a .cdrca file compile to fetch() wrappers that call these routes.
# ---------------------------------------------------------------------
@app.get("/api/users")
def get_users():
    return {"users": db.find("users")}


@app.post("/api/users")
async def create_user(request: Request):
    body = await request.json()
    name = (body.get("name") or "").strip()
    if not name:
        return {"error": "name is required"}
    new_id = db.create("users", {"name": name})
    return db.find_by_id("users", new_id)


# ---------------------------------------------------------------------
# Static assets (css/js/images/fonts) at /assets/...
# ---------------------------------------------------------------------
assets_dir = os.path.join(BASE_DIR, "assets")
if os.path.isdir(assets_dir):
    app.mount("/assets", StaticFiles(directory=assets_dir), name="assets")


# ---------------------------------------------------------------------
# Frontend page.
# ---------------------------------------------------------------------
@app.get("/")
def index():
    return FileResponse(os.path.join(BASE_DIR, "index.html"))


if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("PORT", "8000"))
    reload_enabled = os.environ.get("PYTHONMASTER_RELOAD") == "1"
    print(f"CDRCA_PORT={port}", flush=True)
    if reload_enabled:
        # uvicorn's reloader needs an import string, not the app object,
        # so it can re-import the module after a file change.
        uvicorn.run("main:app", host="127.0.0.1", port=port, reload=True)
    else:
        uvicorn.run(app, host="127.0.0.1", port=port)
